# This is the docker-compose file to run Medplum's required background services
# It can be used to quickly run the Redis cache service
# You can start the service by running "docker-compose up"
version: '3.7'
services:
  redis:
    image: redis:7
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
